{
 "title": "AKS Nginx Ingress",
 "description": "Dashboard for AKS nginx-ingress",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash{app=~\"$app\"}, namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "singlestat",
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[5m])) / sum(rate(nginx_ingress_controller_requests{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_class=~\"$controller_class\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Config Failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nginx_ingress_controller_config_last_reload_successful{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}==0"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "[Ingress] Throughput [rpm]",
   "type": "graph",
   "description": "[rate 1m] [rpm]",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[5m])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "[Ingress] Nginx Connections",
   "type": "graph",
   "description": "Ingress Nginx'es connection types",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total[5m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "2xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"2.*\"}[5m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "3xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"3.*\"}[5m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "4xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"4.*\"}[5m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "5xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"5.*\"}[5m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "RPM Total",
   "type": "singlestat",
   "description": "All Status Code",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[5m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m])) ",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}