{
 "title": "AKS PoD Monitoring",
 "description": "Kubernetes PoD monitoring using prometheus.",
 "tags": [ "Openshift" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "query": "label_values(node)" },
   {
    "name": "Project",
    "query": "label_values(exported_namespace)"
   },
   {
    "name": "PoD",
    "query": "label_values(kube_pod_info{namespace=\"$Project\"},pod)"
   },
   {
    "name": "PoD_Node",
    "query": "label_values(kube_pod_info{namespace=\"$Project\",pod=\"$PoD\"},node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU ",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster Disk",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",image!=\"\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",image!=\"\",node=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "PoD Running",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 9, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum(kubelet_running_pod_count)", "legendFormat": "Running " }
     ]
    },
    {
     "title": "PoD Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 13, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_pods)",
       "legendFormat": "Running "
      }
     ]
    },
    {
     "title": "Container Running",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 9, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kubelet_running_container_count)",
       "legendFormat": "Running "
      }
     ]
    },
    {
     "title": "Node Ready",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 13, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\"} == 1)",
       "legendFormat": "Running "
      }
     ]
    }
   ]
  },
  {
   "title": "PoD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod_name=~\"$PoD\",exported_namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "IN"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod_name=~\"$PoD\",exported_namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod_name)",
       "legendFormat": "OUT"
      }
     ]
    },
    {
     "title": "Pods CPU usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod_name=~\"$PoD\",exported_namespace=~\"^$Project$\",instance=~\"^$Node$\"}[2m])) by (pod_name,instance)",
       "legendFormat": "{{ pod_name }}  ({{ instance }}  )"
      }
     ]
    },
    {
     "title": "Pod Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{instance=\"$PoD\"} |~ \"(established|accepted|empid|WARNING)\""
      }
     ]
    },
    {
     "title": "Pods Memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sort_desc (sum (container_memory_max_usage_bytes{image!=\"\",pod_name=\"$PoD\",exported_namespace=~\"^$Project$\",iinstance=~\"^$Node$\"}) by (pod_name,instance))",
       "legendFormat": "{{ pod_name }}  ({{ instance }}  )"
      }
     ]
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Node CPU ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"$PoD_Node\"}[1m])) / sum (machine_cpu_cores{node=~\"$PoD_Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"$PoD_Node\"}) / sum (machine_memory_bytes{node=~\"$PoD_Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",image!=\"\",node=~\"$PoD_Node\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",image!=\"\",node=~\"$PoD_Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "content": "    $PoD_Node\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count {node=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{node=\"$PoD_Node\"} ",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{node=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"$PoD_Node\"}[10m]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$PoD_Node\"}) - sum(node_memory_MemFree_bytes{instance=\"$PoD_Node\"}) - sum(node_memory_Buffers_bytes{instance=\"$PoD_Node\"}) - sum(node_memory_Cached_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Node load usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 1"
    },
    {
     "expr": "sum(node_load5{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 5"
    },
    {
     "expr": "sum(node_load15{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "Node Disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=\"$PoD_Node\"}[5m])) ",
     "legendFormat": "IO time"
    }
   ]
  },
  {
   "title": "Node Network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum (rate (node_network_transmit_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "node_out"
    },
    {
     "expr": "sum (rate (node_network_transmit_bytes_total{device=\"eth0\",instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "eth0 out"
    }
   ]
  }
 ]
}