apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    name: prometheus-rules
  namespace: kubemon
data:
  alert.rules: |-
    groups:
      - name: Cluster
        rules:
        - alert: Kube API Down
          annotations:
            message: Kubernetes API server down
          expr: |
            up{job="kubernetes-apiserver"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube Controller Down
          annotations:
            message: Kubernetes Controller down
          expr: |
            kube_pod_container_status_running{namespace="kube-system",pod="kube-controller-manager-kube-master"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube Scheduler Down
          annotations:
            message: Kubernetes Scheduler down
          expr: |
            kube_pod_container_status_running{namespace="kube-system",pod="kube-scheduler-kube-master"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube ETCD Down
          annotations:
            message: Kubernetes ETCD down
          expr: |
            kube_pod_container_status_running{namespace="kube-system",pod="etcd-kube-master"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube DNS Down
          annotations:
            message: Kubernetes DNS down
          expr: |
            up{k8s_app="kube-dns",kubernetes_namespace="kube-system"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kubelet Down
          annotations:
            message: Kubernetes Kubelet Down
          expr: |
            up{job="kubernetes-nodes-kubelet"} == 0
          for: 5m
          labels:
            severity: critical            

      - name: Kubernetes-system
        rules:
        - alert: KubeClient Certificate Expiration
          annotations:
            message: A client certificate used to authenticate to the apiserver is expiring in less than 7.0 days.
          expr: |
            sum(apiserver_client_certificate_expiration_seconds_bucket{le="604800"}) > 0
          labels:
            severity: warning
        - alert: KubeClient Certificate Expiration
          annotations:
            message: A client certificate used to authenticate to the apiserver is expiring in less than 24 hrs.
          expr: |
            sum(apiserver_client_certificate_expiration_seconds_bucket{le="86400"}) > 0
          labels:
            severity: critical

        - alert: Node NotReady
          annotations:
            message: Kubernetes Node {{ $labels.node }} NotReady more than 5 minutes
          expr: |
            kube_node_status_condition {k8s_app="kube-state-metrics",condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
            
        - alert: DaemonSet Rollout Stuck
          annotations:
            message: Only % of desired pods scheduled and ready for daemon
          expr: |
            kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled * 100 < 100
          for: 5m
          labels:
            severity: critical    
        - alert: DaemonSet NotScheduled
          annotations:
            message: A number of daemonsets are not scheduled
          expr: |
            kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
          for: 5m
          labels:
            severity: critical    
        - alert: DaemonSet MissScheduled
          annotations:
            message: A number of daemonsets are running where they are not supposed to run.
          expr: |
            kube_daemonset_status_number_misscheduled > 0
          for: 5m
          labels:
            severity: critical              
            
        - alert: Too Many Pods
          annotations:
            message: 'Too Many Pods is running at on node {{ $labels.instance }} (current value: {{ $value }}).'
          expr: |
            max(kubelet_running_pod_count{job="kubernetes-nodes-kubelet"}) by(instance) > 95
          for: 5m
          labels:
            severity: warning

        - alert: Pod CrashLooping
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.'
          expr: |
            rate(kube_pod_container_status_restarts_total{k8s_app="kube-state-metrics"}[5m]) * 60 * 5 > 0
          for: 5m
          labels:
            severity: critical

        - alert: Kube Pod NotReady
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 5 minutes.'
          expr: |
            sum by (namespace, pod) (kube_pod_status_phase{k8s_app="kube-state-metrics", phase=~"Failed|Pending|Unknown"} * on(namespace, pod) group_left(owner_kind) kube_pod_owner{owner_kind!="Job"}) > 0
          for: 5m
          labels:
            severity: critical

        - alert: Kube CPU Overcommit
          annotations:
            message: Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
          expr: |
            sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum) / sum(kube_node_status_allocatable_cpu_cores) > (count(kube_node_status_allocatable_cpu_cores)-1) / count(kube_node_status_allocatable_cpu_cores)
          for: 5m
          labels:
            severity: warning
        - alert: Kube Memory Overcommit
          annotations:
            message: Cluster has overcommitted memory resource requests for Pods and cannot tolerate node failure.
          expr: |
            sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum) / sum(kube_node_status_allocatable_memory_bytes) > (count(kube_node_status_allocatable_memory_bytes)-1) / count(kube_node_status_allocatable_memory_bytes)
          for: 5m
          labels:
            severity: warning

      - name: Deployment
        rules:
        - alert: Deployment at 0 Replicas
          annotations:
            summary: Deployment {{$labels.deployment}} in {{$labels.namespace}} is currently having no pods running
          expr: |
            sum(kube_deployment_status_replicas{pod_template_hash=""}) by (deployment,namespace)  < 1
          for: 1m
          labels:
            severity: critical
        - alert: HPA Scaling Limited
          annotations:
            summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace has reached scaling limited state
          expr: |
            (sum(kube_hpa_status_condition{condition="ScalingLimited",status="true"}) by (hpa,namespace)) == 1
          for: 1m
          labels:
            severity: critical
        - alert: HPA at MaxCapacity
          annotations:
            summary: HPA named {{$labels.hpa}} in {{$labels.namespace}} namespace is running at Max Capacity
          expr: |
            ((sum(kube_hpa_spec_max_replicas) by (hpa,namespace)) - (sum(kube_hpa_status_current_replicas) by (hpa,namespace))) == 0
          for: 1m
          labels:
            severity: critical
      - name: Pods
        rules:
        - alert: Container restarted
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} was restarted
          expr: |
            sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system",pod_template_hash=""}[1m])) by (pod,namespace,container) > 0
          for: 0m
          labels:
            severity: warning
        - alert: High Memory Usage of Container
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of Memory Limit
          expr: |
            ((( sum(container_memory_usage_bytes{image!="",container_name!="POD", namespace!="kube-system"}) by (namespace,container_name,pod_name)  / sum(container_spec_memory_limit_bytes{image!="",container_name!="POD",namespace!="kube-system"}) by (namespace,container_name,pod_name) ) * 100 ) < +Inf ) > 75
          for: 5m
          labels:
            severity: warning
        - alert: High CPU Usage of Container
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} is using more than 75% of CPU Limit
          expr: |
            ((sum(irate(container_cpu_usage_seconds_total{image!="",container_name!="POD", namespace!="kube-system"}[30s])) by (namespace,container_name,pod_name) / sum(container_spec_cpu_quota{image!="",container_name!="POD", namespace!="kube-system"} / container_spec_cpu_period{image!="",container_name!="POD", namespace!="kube-system"}) by (namespace,container_name,pod_name) ) * 100)  > 75
          for: 5m
          labels:
            severity: warning
      - name: Nodes
        rules:
        - alert: High Node Memory Usage
          annotations:
            summary: Node {{$labels.kubernetes_io_hostname}} has more than 80% memory used. Plan Capcity
          expr: |
            (sum (container_memory_working_set_bytes{id="/",container_name!="POD"}) by (kubernetes_io_hostname) / sum (machine_memory_bytes{}) by (kubernetes_io_hostname) * 100) > 80
          for: 5m
          labels:
            severity: critical
        - alert: High Node CPU Usage
          annotations:
            summary: Node {{$labels.kubernetes_io_hostname}} has more than 80% allocatable cpu used. Plan Capacity.
          expr: |
            (sum(rate(container_cpu_usage_seconds_total{id="/", container_name!="POD"}[1m])) by (kubernetes_io_hostname) / sum(machine_cpu_cores) by (kubernetes_io_hostname)  * 100) > 80
          for: 5m
          labels:
            severity: critical
        - alert: High Node Disk Usage
          annotations:
            summary: Node {{$labels.kubernetes_io_hostname}} has more than 85% disk used. Plan Capacity.
          expr: |
            (sum(container_fs_usage_bytes{device=~"^/dev/[sv]d[a-z][1-9]$",id="/",container_name!="POD"}) by (kubernetes_io_hostname) / sum(container_fs_limit_bytes{container_name!="POD",device=~"^/dev/[sv]d[a-z][1-9]$",id="/"}) by (kubernetes_io_hostname)) * 100 > 85
          for: 5m
          labels:
            severity: critical
