apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
  name: loki
  namespace: kubelog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fluent-bit-loki
  name: loki-fluent-bit-loki
  namespace: kubelog
