apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
  namespace: kubelog    
spec:
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: loki
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  labels:
    app: loki
  namespace: kubelog    
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
  sessionAffinity: None
  type: ClusterIP
