apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    name: prometheus-rules
  namespace: kubemon
data:
  alert.rules: |-
    groups:
      - name: Cluster
        rules:
        - alert: Kube API Down
          annotations:
            message: Kubernetes API server down
          expr: |
            up{job="kubernetes-apiservers"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube Proxy Down
          annotations:
            message: Kubernetes Proxy down
          expr: |
            kube_pod_container_status_running{container="kube-proxy",namespace="kube-system"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube DNS Down
          annotations:
            message: Kubernetes DNS down
          expr: |
            kube_pod_container_status_running{container="coredns",namespace="kube-system"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kubelet Down
          annotations:
            message: Kubernetes Kubelet Down
          expr: |
            up{job="kubelet"} == 0
          for: 5m
          labels:
            severity: critical            
        - alert: Node Expoter Down
          annotations:
            message: Node Expoter Down
          expr: |
            up{job="kubernetes-nodes-exporter"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Kube State Metric Down
          annotations:
            message: Kube State Metric Down
          expr: |
            up{job="kube-state-metrics"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: Ingress Controller Down
          annotations:
            message: Kube Ingress Controller Down
          expr: |
            up{job="ingress-nginx"} == 0
          for: 5m
          labels:
            severity: critical

      - name: Kubernetes-system
        rules:
        - alert: Kubernetes Certificate Expiration
          annotations:
            message: A client certificate used to authenticate to the apiserver is expiring in less than 7.0 days.
          expr: |
            sum(apiserver_client_certificate_expiration_seconds_bucket{le="604800"}) > 0
          labels:
            severity: warning
        - alert: Kubernetes Certificate Expiration
          annotations:
            message: A client certificate used to authenticate to the apiserver is expiring in less than 24 hrs.
          expr: |
            sum(apiserver_client_certificate_expiration_seconds_bucket{le="86400"}) > 0
          labels:
            severity: critical
        - alert: Node NotReady
          annotations:
            message: Kubernetes Node {{ $labels.node }} NotReady more than 5 minutes
          expr: |
            kube_node_status_condition {job="kube-state-metrics",condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
        - alert: DaemonSet Rollout Stuck
          annotations:
            message: Only % of desired pods scheduled and ready for daemon
          expr: |
            kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled * 100 < 100
          for: 5m
          labels:
            severity: critical    
        - alert: DaemonSet NotScheduled
          annotations:
            message: A number of daemonsets are not scheduled
          expr: |
            kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
          for: 5m
          labels:
            severity: critical    
        - alert: DaemonSet MissScheduled
          annotations:
            message: A number of daemonsets are running where they are not supposed to run.
          expr: |
            kube_daemonset_status_number_misscheduled > 0
          for: 5m
          labels:
            severity: critical              
        - alert: Too Many Pods
          annotations:
            message: 'Too Many Pods is running at on node {{ $labels.node }} (current value: {{ $value }}).'
          expr: |
            max(kubelet_running_pod_count{job="kubelet"}) by(node) > 95
          for: 5m
          labels:
            severity: warning
        - alert: Pod CrashLooping
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.'
          expr: |
            rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[5m]) * 60 * 5 > 0
          for: 5m
          labels:
            severity: critical
        - alert: Pod Waiting
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is waiting for this reason ({{ $labels.reason }})'
          expr: |
            sum by(namespace, pod, reason) (kube_pod_container_status_waiting_reason{job="kube-state-metrics",reason=~"CrashLoopBackOff|ErrImagePull|ImagePullBackOff"} * on(namespace, pod) group_left(owner_kind) kube_pod_owner{owner_kind!="Job"}) > 0
          for: 5m
          labels:
            severity: critical
        - alert: Pod Frequently Restarting
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting frequently'
          expr: |
            increase(kube_pod_container_status_restarts_total[5m]) > 5
          for: 5m
          labels:
            severity: critical            
        - alert: Kube Pod NotReady
          annotations:
            message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state ({{ $labels.phase }}) for longer than 5 minutes.'
          expr: |
            sum by (namespace, pod, phase) (kube_pod_status_phase{job="kube-state-metrics", phase=~"Failed|Pending|Unknown"} * on(namespace, pod) group_left(owner_kind) kube_pod_owner{owner_kind!="Job"}) > 0
          for: 5m
          labels:
            severity: critical
        - alert: Container Killed
          annotations:
            summary: "Container killed (instance {{ $labels.instance }})"
            description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            time() - container_last_seen > 60
          for: 5m
          labels:
            severity: warning
        - alert: Container Volume Usage
          annotations:
            summary: "Container Volume usage (instance {{ $labels.instance }})"
            description: "Container Volume usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            (1 - (sum(container_fs_inodes_free) BY (ip) / sum(container_fs_inodes_total) BY (ip)) * 100) > 80
          for: 5m
          labels:
            severity: warning
        - alert: Container Volume IO Usage
          annotations:
            summary: "Container Volume IO usage (instance {{ $labels.instance }})"
            description: "Container Volume IO usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            (sum(container_fs_io_current) BY (ip, name) * 100) > 80
          for: 5m
          labels:
            severity: warning
        - alert: Kube Memory pressure
          annotations:
            summary: "Kubernetes MemoryPressure (instance {{ $labels.instance }})"
            description: "{{ $labels.node }} has MemoryPressure condition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
          for: 5m
          labels:
            severity: error
        - alert: Kube Disk pressure
          annotations:
            summary: "Kubernetes DiskPressure (instance {{ $labels.instance }})"
            description: "{{ $labels.node }} has DiskPressure condition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 5m
          labels:
            severity: error
        - alert: Kube Out of disk
          annotations:
            summary: "Kubernetes OutOfDisk (instance {{ $labels.instance }})"
            description: "{{ $labels.node }} has OutOfDisk condition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            kube_node_status_condition{condition="OutOfDisk",status="true"} == 1
          for: 5m
          labels:
            severity: error
        - alert: Statefulset Down
          annotations:
            summary: "StatefulSet down (instance {{ $labels.instance }})"
            description: "A StatefulSet went down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            (kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current) != 1
          for: 5m
          labels:
            severity: error

      - name: Deployment
        rules:
        - alert: Deployment at 0 Replicas
          annotations:
            summary: Deployment {{$labels.deployment}} in {{$labels.namespace}} is currently having no pods running
          expr: |
            sum(kube_deployment_status_replicas{pod_template_hash=""}) by (deployment,namespace)  < 1
          for: 1m
          labels:
            severity: critical

      - name: Pods
        rules:
        - alert: Container restarted
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.namespace}} was restarted
          expr: |
            sum(increase(kube_pod_container_status_restarts_total{namespace!="kube-system",pod_template_hash=""}[1m])) by (pod,namespace,container) > 0
          for: 0m
          labels:
            severity: warning
        - alert: High Memory Usage of Container
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.exported_namespace}} is using more than 75% of Memory Limit
          expr: |
            (((sum by(exported_namespace, container_name, pod_name) (container_memory_usage_bytes{container_name!="POD",image!="",exported_namespace!="kube-system"}) / sum by(exported_namespace, container_name, pod_name) (container_spec_memory_limit_bytes{container_name!="POD",image!="",exported_namespace!="kube-system"})) * 100) < +Inf) > 75
          for: 5m
          labels:
            severity: warning
        - alert: High CPU Usage of Container
          annotations:
            summary: Container named {{$labels.container}} in {{$labels.pod}} in {{$labels.exported_namespace}} is using more than 75% of CPU Limit
          expr: |
            ((sum by(exported_namespace, container_name, pod_name) (irate(container_cpu_usage_seconds_total{container_name!="POD",image!="",exported_namespace!="kube-system"}[30s])) / sum by(exported_namespace, container_name, pod_name) (container_spec_cpu_quota{container_name!="POD",image!="",exported_namespace!="kube-system"} / container_spec_cpu_period{container_name!="POD",image!="",exported_namespace!="kube-system"})) * 100) > 75
          for: 5m
          labels:
            severity: warning

        - alert: POD terminated
          annotations:
            description: 'Pod {{$labels.pod}} in namespace {{$labels.namespace}} has a container terminated for more than 10 minutes'
            summary: 'Pod {{$labels.pod}} in namespace {{$labels.namespace}} in error status'
          expr: |
            kube_pod_container_status_terminated_reason{reason=~"OOMKilled|Error|ContainerCannotRun"} > 0
          for: 10m
          labels:
            severity: page

      - name: Ingress
        rules:
        - alert: HTTP Errors 4xx
          annotations:
            summary: "HTTP errors 4xx (instance {{ $labels.ingress }})"
            description: "Too many HTTP requests with status 4xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            sum(rate(nginx_ingress_controller_requests{ingress!="",status=~"^4.."}[1m])) / sum(rate(nginx_ingress_controller_requests[1m])) * 100 > 5
          for: 5m
          labels:
            severity: error
        - alert: HTTP Errors 5xx
          annotations:
            summary: "HTTP errors 5xx (instance {{ $labels.ingress }})"
            description: "Too many HTTP requests with status 5xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            sum(rate(nginx_ingress_controller_requests{ingress!="",status=~"^5.."}[1m])) / sum(rate(nginx_ingress_controller_requests[1m])) * 100 > 5
          for: 5m
          labels:
            severity: error

      - name: Nodes
        rules:
        - alert: High Node Memory Usage
          annotations:
            summary: Node {{$labels.kubernetes_io_hostname}} has more than 80% memory used. Plan Capcity
          expr: |
            ((node_memory_MemTotal_bytes) - ((node_memory_MemFree_bytes) + (node_memory_Buffers_bytes) + (node_memory_Cached_bytes))) / (node_memory_MemTotal_bytes) * 100 > 80
          for: 5m
          labels:
            severity: critical
        - alert: High Node CPU Usage
          annotations:
            summary: Node {{$labels.node}} has more than 80% allocatable cpu used. Plan Capacity.
          expr: |
            (sum by(node) (rate (container_cpu_usage_seconds_total{image!="",name=~"^k8s_.*"}[1m])) / sum by(node)  (machine_cpu_cores) * 100) > 80
          for: 5m
          labels:
            severity: critical
        - alert: High Node Disk1 Usage root FS
          annotations:
            summary: Node {{$labels.instance}} has more than 90% disk used in {{$labels.agentpool}} Nodepool. Plan Capacity.
            description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            node_filesystem_free_bytes{mountpoint ="/rootfs"} / node_filesystem_size_bytes{mountpoint ="/rootfs"} * 100 < 10
          for: 5m
          labels:
            severity: critical
        - alert: High Node Disk2 Usage mnt FS
          annotations:
            summary: Node {{$labels.instance}} has more than 90% disk used in {{$labels.agentpool}} Nodepool. Plan Capacity.
            description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            node_filesystem_free_bytes{mountpoint ="/rootfs/mnt"} / node_filesystem_size_bytes{mountpoint ="/rootfs/mnt"} * 100 < 10
          for: 5m
          labels:
            severity: critical
        - alert: Unusual Disk Read Rate
          annotations:
            summary: "Unusual disk read rate (instance {{ $labels.instance }})"
            description: "Disk is probably reading too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            sum by (instance,device) (irate(node_disk_read_bytes_total{device=~"sd[a-z]"}[2m])) / 1024 / 1024 > 50
          for: 5m
          labels:
            severity: warning
        - alert: Unusual Disk Write Rate
          annotations:
            summary: "Unusual disk write rate (instance {{ $labels.instance }})"
            description: "Disk is probably writing too much data (> 50 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            #sum by(instance,device) (irate(node_disk_written_bytes_total{device=~"sd[a-z]"}[2m])) / 1024 / 1024 > 50
            sum by(instance,device) (irate(node_disk_written_bytes_total{device=~"sd[a-z]"}[2m])) / 1024 / 1024 > 25
          for: 5m
          labels:
            severity: warning
        - alert: Unusual Disk Read Latency
          annotations:
            summary: "Unusual disk read latency (instance {{ $labels.instance }})"
            description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
          for: 5m
          labels:
            severity: warning
        - alert: Unusual Network Throughput In
          annotations:
            summary: "Unusual network throughput in (instance {{ $labels.instance }})"
            description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
          for: 5m
          labels:
            severity: warning
        - alert: Unusual Network Throughput Out
          annotations:
            summary: "Unusual network throughput out (instance {{ $labels.instance }})"
            description: "Host network interfaces are probably sending too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            sum by (instance) (irate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
          for: 5m
          labels:
            severity: warning
        - alert: Out Of Inodes
          annotations:
            summary: "Out of inodes (instance {{ $labels.instance }})"
            description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint ="/rootfs"} * 100 < 10
          for: 5m
          labels:
            severity: warning
        - alert: Unusual Disk Write Latency
          annotations:
            summary: "Unusual disk write latency (instance {{ $labels.instance }})"
            description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 100
          for: 5m
          labels:
            severity: warning
        - alert: High CPU Load
          annotations:
            summary: "High CPU load (instance {{ $labels.instance }})"
            description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          expr: |
            100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
